# Generated by Django 3.0.5 on 2020-04-22 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='000000', help_text='Commercial Office name', max_length=64, unique=True, verbose_name='Name')),
                ('email', models.CharField(help_text='Commercial Office E-mail', max_length=64, verbose_name='E-Mail')),
                ('telephone', models.CharField(help_text='Commercial Office Telephone', max_length=64, verbose_name='Telephone')),
            ],
            options={
                'verbose_name': 'Commercial Office',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(default='000000', help_text='Commercial Office name', max_length=64, unique=True, verbose_name='Contract number')),
                ('route', models.CharField(max_length=6, null=True, verbose_name='Collection route')),
                ('number', models.IntegerField(null=True, verbose_name='Folio')),
                ('reading', models.CharField(default='00000', help_text='Meter selfreading', max_length=6, verbose_name='Reading')),
                ('reading_date', models.DateField(blank=True, default=datetime.datetime(2020, 4, 22, 21, 25, 48, 748320, tzinfo=utc), null=True, verbose_name='Booking date')),
                ('commercial_office_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectura.CommercialOffice', verbose_name='Commercial Office')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'ordering': ('contract_number',),
            },
        ),
    ]
