# Generated by Django 3.0.5 on 2020-04-22 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Booking date'),
        ),
    ]
