# Generated by Django 3.0.5 on 2020-04-22 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectura', '0002_auto_20200422_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Reading date'),
        ),
    ]
